[LightDM]
session-wrapper=/etc/lightdm/Xsession
start-default-seat=true

[Seat:*]
xserver-command=X -listen tcp
xserver-allow-tcp=true
autologin-user=kellykaoudis
autologin-user-timeout=0
user-session=ubuntu
